services:
  fastapi_app:
    container_name: fastapi_app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
  # nginx_proxy:
  #   container_name: nginx_proxy
  #   image: nginx:1.29-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./app/static:/var/www/static:ro
